### get all users
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6Imt1a2thcnV1a2t1IiwiZW1haWwiOiJ4eEBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTExVDAzOjA3OjIwLjAwMFoiLCJ1c2VyX2xldmVsIjoiYWRtaW4iLCJpYXQiOjE3NDI2MjgyMDh9.-aWFI6H05fdO9Pybj8WJcZDEV1jd3nmbRtaghJgK7vk

### get user by id
GET http://localhost:3000/api/users/7

### create a new user (user registration)
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "kukkaruukku",
  "password": "kissankello",
  "email": "xx@example.com"
}

### modify an existing user by id
PUT http://localhost:3000/api/users/3
content-type: application/json

{
  "username": "editedname",
  "password": "editedpasswordx",
  "email": "editedmail@example.com"
}

### delete a user (by id)
DELETE http://localhost:3000/api/users/3

### user login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "kukkaruukku",
  "password": "kissankello"
}

### get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6Imt1a2thcnV1a2t1IiwiZW1haWwiOiJ4eEBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTExVDAzOjA3OjIwLjAwMFoiLCJ1c2VyX2xldmVsIjoiYWRtaW4iLCJpYXQiOjE3NDI2MjgyMDh9.-aWFI6H05fdO9Pybj8WJcZDEV1jd3nmbRtaghJgK7vk

## (Diary)Entries

### post a new entry
POST http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6Imt1a2thcnV1a2t1IiwiZW1haWwiOiJ4eEBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTExVDAzOjA3OjIwLjAwMFoiLCJ1c2VyX2xldmVsIjoiYWRtaW4iLCJpYXQiOjE3NDI2MjgyMDh9.-aWFI6H05fdO9Pybj8WJcZDEV1jd3nmbRtaghJgK7vk
content-type: application/json

{
 "entry_date": "2025-02-25",
 "anxiety_level": 2,
 "notes": "iloinen"
}

### Get user's entries
GET http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6Imt1a2thcnV1a2t1IiwiZW1haWwiOiJ4eEBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTExVDAzOjA3OjIwLjAwMFoiLCJ1c2VyX2xldmVsIjoiYWRtaW4iLCJpYXQiOjE3NDI2MjgyMDh9.-aWFI6H05fdO9Pybj8WJcZDEV1jd3nmbRtaghJgK7vk
